### ISSUE TITLE
Failed during `./m1_homebrew install`

### ISSUE THREAD

**Issue by zedchance** [pforret/macos_m1_cli#4]
Hi, thanks for making this migration script as I was currently looking into how to migrate to the new installation path.

When I ran `./m1_homebrew install` the script failed with this error:
```
❯ ./m1_homebrew install
Program: m1_homebrew 1.3.2
✔  MacOS version = 11.1
✔  Script running in arm64 mode
Are you sure you want to install Homebrew for arm64 to /opt/homebrew? [y/N] y
…  Download Homebrew into [/Users/zedchance/.homebrew] ...

✔  After download: Homebrew folder is 15 MB
✔  After update  : Homebrew folder is 65 MB
✔  After install : Homebrew folder is 464 MB
…  Move Homebrew files to /opt/homebrew
Password:g /Users/zedchance/.homebrew/bin ...
Sorry, try again.
Password:
Create folder share/zshance/.homebrew/SECURITY.md ...
Create folder share/zsh/site-functions
Create folder Caskroom
✔  All files moved to /opt/homebrew
/Users/zedchance/.zshrc: line 4: ${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh: bad substitution
/Users/zedchance/.oh-my-zsh/oh-my-zsh.sh: line 6: ZSH_CACHE_DIR: unbound variable
✖ m1_homebrew: ERROR 1 after 229 seconds
> last command : '[[ -z "$ZSH_CACHE_DIR" ]]'
${error_prefix} from line 188 :     zsh)    startup_config "$architecture" "$HOMEBREW_PREFIX" "$script_prefix-$architecture" >> "$HOME/.zshrc"  ; source "$HOME/.zshrc" ;;
```

It looks like it has something to do with either my installation of [`oh-my-zsh`](https://ohmyz.sh) or [`powerline10k`](https://github.com/romkatv/powerlevel10k)? Any help is appreciated!

**Comment by pforret** [comment]
Could you show me what your .zshrc looks like? I'd like to see if the script added its 2 lines to it correctly.

**Comment by zedchance** [comment]
It did add 2 lines at the end, here check out the full file here https://gist.github.com/zedchance/42c73e3ea747f1da5033b3f5214b25a5

**Comment by pforret** [comment]
That seems correct. After I add these 2 lines, I re-source .zshrc to have the latest settings.
It seems that's where your error pops up.

I removed that full -re -source of .zshrc and just execute the lines that have been added.
Try v1.3.3!

**Comment by zedchance** [comment]
That worked, thanks!
